[tool.poetry]
name = "systems-theory-project"
version = "0.1.0"
description = ""
authors = ["FranDeLio <franciscodelioperego@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^2.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
